apiVersion: v1
kind: Service
metadata:
  name: otc-pricing-mcp
  namespace: mcp-otc-pricing
  labels:
    app: otc-pricing-mcp
spec:
  type: ClusterIP
  selector:
    app: otc-pricing-mcp
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
